### ISSUE TITLE
Balance fetch fails with INVALID_FIELD error - missing min_last_updated_datetime parameter

### ISSUE THREAD

**Issue by Maralai** [dvankley/firefly-plaid-connector-2#124]
## Error Description
When fetching balances, the application fails with an INVALID_FIELD error indicating that the `min_last_updated_datetime` parameter is required for balance requests on institution `ins_128026`.

## Error Message
```plaintext
"error_code": "INVALID_FIELD",
"error_message": "min_last_updated_datetime parameter required for balance on ins_128026",
"error_type": "INVALID_REQUEST"
```

## Technical Details
- The parameter appears to be defined in the test file: [PlaidApiWrapperTest.kt#L287](https://github.com/dvankley/firefly-plaid-connector-2/blob/c45c28a2a973764eca176a5795f1a03d650c3d46/src/test/kotlin/net/djvk/fireflyPlaidConnector2/api/plaid/PlaidApiWrapperTest.kt#L287)
- However, it seems this parameter is not being included in the actual API calls in the production code

## Suggested Fix
Add the required `min_last_updated_datetime` parameter to the balance request in the production code, similar to how it's implemented in the test file.

## Stack Trace
<details>
<summary>Full stack trace</summary>

```plaintext
2024-12-31T01:19:11.097Z DEBUG 1 --- [main] n.d.f.sync.BatchSyncRunner : Requesting balances for access token [ACCESS_TOKEN_REDACTED] and account ids [ACCOUNT_IDS_REDACTED]
2024-12-31T01:19:11.474Z ERROR 1 --- [main] n.d.f.sync.BatchSyncRunner : Failed to fetch balances for access token [ACCESS_TOKEN_REDACTED] and account ids [ACCOUNT_IDS_REDACTED]
io.ktor.client.plugins.ClientRequestException: Client request(POST https://production.plaid.com/accounts/balance/get) invalid: 400 Bad Request. Text: "{
  "display_message": null,
  "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
  "error_code": "INVALID_FIELD",
  "error_message": "min_last_updated_datetime parameter required for balance on ins_128026",
  "error_type": "INVALID_REQUEST",
  "request_id": "tdArpJPx9vm0uRx",
  "suggested_action": null
}"
        at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:54) ~[ktor-client-core-jvm-2.3.12.jar:2.3.12]
        at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt) ~[ktor-client-core-jvm-2.3.12.jar:2.3.12]
        at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt) ~[ktor-client-core-jvm-2.3.12.jar:2.3.12]
        at io.ktor.client.plugins.HttpCallValidator.validateResponse(HttpCallValidator.kt:51) ~[ktor-client-core-jvm-2.3.12.jar:2.3.12]
        at io.ktor.client.plugins.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:43) ~[ktor-client-core-jvm-2.3.12.jar:2.3.12]
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:152) ~[ktor-client-core-jvm-2.3.12.jar:2.3.12]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.9.24.jar:1.9.24-release-822]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at net.djvk.fireflyPlaidConnector2.sync.BatchSyncRunner.run(BatchSyncRunner.kt:54) ~[classes/:1.3.2]
        at net.djvk.fireflyPlaidConnector2.FireflyPlaidConnector2Application.appReady(FireflyPlaidConnector2Application.kt:23) ~[classes/:1.3.2]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:365) ~[spring-context-6.1.11.jar:6.1.11]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:237) ~[spring-context-6.1.11.jar:6.1.11]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168) ~[spring-context-6.1.11.jar:6.1.11]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185) ~[spring-context-6.1.11.jar:6.1.11]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-6.1.11.jar:6.1.11]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156) ~[spring-context-6.1.11.jar:6.1.11]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:452) ~[spring-context-6.1.11.jar:6.1.11]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:385) ~[spring-context-6.1.11.jar:6.1.11]
        at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:109) ~[spring-boot-3.3.2.jar:3.3.2]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:80) ~[spring-boot-3.3.2.jar:3.3.2]
        at java.base/java.lang.Iterable.forEach(Unknown Source) ~[na:na]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118) ~[spring-boot-3.3.2.jar:3.3.2]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112) ~[spring-boot-3.3.2.jar:3.3.2]
        at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:80) ~[spring-boot-3.3.2.jar:3.3.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:349) ~[spring-boot-3.3.2.jar:3.3.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.2.jar:3.3.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.2.jar:3.3.2]
        at net.djvk.fireflyPlaidConnector2.FireflyPlaidConnector2ApplicationKt.main(FireflyPlaidConnector2Application.kt:31) ~[classes/:1.3.2]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[workspace/:na]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[workspace/:na]
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[workspace/:na]  
```

</details>

**Comment by dvankley** [comment]
Should be fixed in https://github.com/dvankley/firefly-plaid-connector-2/releases/tag/v1.3.3.
