### ISSUE TITLE
Polled run fails

### ISSUE THREAD

**Issue by ch4ndu** [dvankley/firefly-plaid-connector-2#6]
Polled run fails with the error below.
I had to create the `plaid_sync_cursors` file and did verify the permissions are updated properly. 
Also, my batched run keeps going in loop without ending. 
I'm guessing this is probably the reason for it too...so not creating new ticket for that at the moment. I will add logs for the batched mode in the comment.
2023-05-05 19:26:44.537 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
HandlerMethod details: 
Bean [net.djvk.fireflyPlaidConnector2.FireflyPlaidConnector2Application$$EnhancerBySpringCGLIB$$183f6f7f]
Method [public void net.djvk.fireflyPlaidConnector2.FireflyPlaidConnector2Application.appReady()]
Resolved arguments: 
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:361) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82) ~[spring-boot-2.7.3.jar:2.7.3]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.3.jar:2.7.3]
	at net.djvk.fireflyPlaidConnector2.FireflyPlaidConnector2ApplicationKt.main(FireflyPlaidConnector2Application.kt:31) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[workspace/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[workspace/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[workspace/:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[workspace/:na]
Caused by: java.io.FileNotFoundException: /opt/fpc-cursors/plaid_sync_cursors.txt (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method) ~[na:na]
	at java.base/java.io.FileOutputStream.open(Unknown Source) ~[na:na]
	at java.base/java.io.FileOutputStream.<init>(Unknown Source) ~[na:na]
	at java.base/java.io.FileOutputStream.<init>(Unknown Source) ~[na:na]
	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108) ~[kotlin-stdlib-1.7.10.jar:1.7.10-release-333(1.7.10)]
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134) ~[kotlin-stdlib-1.7.10.jar:1.7.10-release-333(1.7.10)]
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134) ~[kotlin-stdlib-1.7.10.jar:1.7.10-release-333(1.7.10)]
	at net.djvk.fireflyPlaidConnector2.sync.PolledSyncRunner$writeCursorMap$2.invokeSuspend(PolledSyncRunner.kt:286) ~[classes/:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.10.jar:1.7.10-release-333(1.7.10)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
2023-05-05 19:26:44.542  INFO 1 --- [           main] n.d.f.sync.PolledSyncRunner              : Shutting down class net.djvk.fireflyPlaidConnector2.sync.PolledSyncRunner

**Comment by ch4ndu** [comment]
Log for batched mode. I don't see any errors here...but the process just doesnt stop and goes on until I stop the container. Let me know if you want to track this in a separate issue

2023-04-25 06:35:06.642  INFO 1 --- [           main] n.d.f.sync.BatchSyncRunner               : Attempting to set initial balances
2023-04-25 06:35:06.642 DEBUG 1 --- [           main] n.d.f.sync.BatchSyncRunner               : Requesting balances for access token XXXX and account ids XXXX
2023-04-25 06:35:10.523 DEBUG 1 --- [           main] n.d.f.sync.BatchSyncRunner               : Inserting initial balance XXX for Firefly account id 1
2023-04-25 06:35:10.523 DEBUG 1 --- [           main] n.d.f.sync.SyncHelper                    : Optimistic insert of 1 txs into Firefly
2023-04-25 06:35:10.599  INFO 1 --- [           main] n.d.f.sync.SyncHelper                    : Skipped transaction null that Firefly identified as a duplicate
Native Memory Tracking:
Total: reserved=17747673010, committed=336412594
-                 Java Heap (reserved=16642998272, committed=167772160)
                            (mmap: reserved=16642998272, committed=167772160) 
 
-                     Class (reserved=72177644, committed=5920748)
                            (classes #9200)
                            (  instance classes #8573, array classes #627)
                            (malloc=874476 #19163) 
                            (mmap: reserved=71303168, committed=5046272) 
                            (  Metadata:   )
                            (    reserved=41943040, committed=39124992)
                            (    used=38861936)
                            (    waste=263056 =0.67%)
                            (  Class space:)
                            (    reserved=71303168, committed=5046272)
                            (    used=4879552)
                            (    waste=166720 =3.30%)
 
-                    Thread (reserved=27434424, committed=2190776)
                            (thread #26)
                            (stack: reserved=27344896, committed=2101248)
                            (malloc=51896 #202) 
                            (arena=37632 #64)
 
-                      Code (reserved=255495400, committed=26766568)
                            (malloc=1862888 #8910) 
                            (mmap: reserved=253632512, committed=24903680) 
 
-                        GC (reserved=661788243, committed=50402899)
                            (malloc=10352211 #9349) 
                            (mmap: reserved=651436032, committed=40050688) 
 
-                  Compiler (reserved=14292496, committed=14292496)
                            (malloc=144928 #1025) 
                            (arena=14147568 #14)
 
-                  Internal (reserved=414697, committed=414697)
                            (malloc=377833 #10615) 
                            (mmap: reserved=36864, committed=36864) 
 
-                     Other (reserved=59392, committed=59392)
                            (malloc=59392 #12) 
 
-                    Symbol (reserved=10405368, committed=10405368)
                            (malloc=9774904 #220902) 
                            (arena=630464 #1)
 
-    Native Memory Tracking (reserved=4375168, committed=4375168)
                            (malloc=7808 #112) 
                            (tracking overhead=4367360)
 
-        Shared class space (reserved=12582912, committed=10981376)
                            (mmap: reserved=12582912, committed=10981376) 
 
-               Arena Chunk (reserved=3227896, committed=3227896)
                            (malloc=3227896) 
 
-                   Tracing (reserved=345, committed=345)
                            (malloc=345 #9) 
 
-                 Arguments (reserved=169, committed=169)
                            (malloc=169 #5) 
 
-                    Module (reserved=177432, committed=177432)
                            (malloc=177432 #1045) 
 
-                 Safepoint (reserved=8192, committed=8192)
                            (mmap: reserved=8192, committed=8192) 
 
-           Synchronization (reserved=68336, committed=68336)
                            (malloc=68336 #772) 
 
-            Serviceability (reserved=672, committed=672)
                            (malloc=672 #6) 
 
-                 Metaspace (reserved=42122816, committed=39304768)
                            (malloc=179776 #124) 
                            (mmap: reserved=41943040, committed=39124992) 
 
-      String Deduplication (reserved=704, committed=704)
                            (malloc=704 #8) 
 
-           Object Monitors (reserved=42432, committed=42432)
                            (malloc=42432 #204) 
 
Setting Active Processor Count to 4
Calculating JVM memory based on 16631824K available memory
For more information on this calculation, see https://paketo.io/docs/reference/java-reference/#memory-calculator
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -Xmx16240145K -XX:MaxMetaspaceSize=84478K -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: 16631824K, Thread Count: 50, Loaded Class Count: 12501, Headroom: 0%)
Enabling Java Native Memory Tracking
Adding 124 container CA certificates to JVM truststore
Spring Cloud Bindings Enabled
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -XX:+ExitOnOutOfMemoryError -XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=10M -Xmx16240145K -XX:MaxMetaspaceSize=84478K -XX:ReservedCodeCacheSize=240M -Xss1M -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+PrintNMTStatistics -Dorg.springframework.cloud.bindings.boot.enable=true
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.3)
2023-04-25 06:35:12.769  INFO 1 --- [           main] .d.f.FireflyPlaidConnector2ApplicationKt : Starting FireflyPlaidConnector2ApplicationKt using Java 17.0.5 on 57cbb112dac7 with PID 1 (/workspace/BOOT-INF/classes started by cnb in /workspace)
2023-04-25 06:35:12.772 DEBUG 1 --- [           main] .d.f.FireflyPlaidConnector2ApplicationKt : Running with Spring Boot v2.7.3, Spring v5.3.22
2023-04-25 06:35:12.773  INFO 1 --- [           main] .d.f.FireflyPlaidConnector2ApplicationKt : No active profile set, falling back to 1 default profile: "default"
2023-04-25 06:35:15.645  INFO 1 --- [           main] .d.f.FireflyPlaidConnector2ApplicationKt : Started FireflyPlaidConnector2ApplicationKt in 3.562 seconds (JVM running for 4.102)

**Comment by ch4ndu** [comment]
This is my compose file for running the container
```
plaid-connector:
    image: ghcr.io/dvankley/firefly-plaid-connector-2:latest
    restart: always
    depends_on:
      - app
    environment:
      - PUID=1026
      - PGID=100
      - SPRING_CONFIG_LOCATION=/opt/fpc-config/application.yml
      - FIREFLYPLAIDCONNECTOR2_POLLED_CURSORFILEDIRECTORYPATH=/opt/fpc-cursors
    volumes:
        - type: bind
          source: /volume2/docker/plaid2/application.yml
          target: /opt/fpc-config/application.yml
          read_only: true
        - type: bind
          source: /volume2/docker/plaid2/cursors
          target: /opt/fpc-cursors
```

**Comment by dvankley** [comment]
>Also, my batched run keeps going in loop without ending.

That's because the docker compose file's restart policy is set to `always`. Remove that or explicitly set it to `no` and it'll stop doing that.

**Comment by dvankley** [comment]
Regarding the issue with the polled run failing, that's because the given docker compose file doesn't mount the volume in such a way that the runtime container's user, `cnb`, can write to it, which is an oversight on my part.

I've added separate docker compose files in https://github.com/dvankley/firefly-plaid-connector-2/commit/214ded20df61b1c63830336d6c1d12dd0ee51b85 and updated the README to make this more clear.

Given the docker compose file you provided, I'd say make sure `/volume2/docker/plaid2/cursors` is writeable by all so that the `cnb` user in the container can write to it.

**Comment by ch4ndu** [comment]
Works now 👍
